---
inherit_gem:
  theforeman-rubocop:
    - strictest.yml

inherit_mode:
  merge:
    - Exclude

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/models/foreman_resource_quota/resource_quota.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/models/concerns/foreman_resource_quota/host_managed_extensions.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'test/**/*.rb'

Naming/FileName:
  Exclude:
    - 'db/seeds.d/**/*'

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*'
    - 'db/seeds.d/**/*'

Style/FormatStringToken:
  Enabled: false
