---
inherit_gem:
  theforeman-rubocop:
    - strictest.yml

inherit_mode:
  merge:
    - Exclude

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - 'test/**/*.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*'

Style/FormatStringToken:
  Enabled: false
